---
- name: play Hello World
  hosts: default
  become: true
  gather_facts: no

  tasks:
    - name: task Hello World
      shell: 'echo "Hello World!\n$(lsb_release -a)"'
      register: hello_world

    - debug: msg="{{ hello_world.stdout }}"
